# -*- coding: utf-8 -*-
"""SunAnalysis-TensorFlow.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wEoQatHkgEILRksJq-WHErUC3mqFMOSF

ANALISIS REGISTRO AGO DHO 9190 2020-03-26T00.00.00 
BASE DE DATOS DE STANDFORD:  http://sid.stanford.edu/database-browser/
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas import DataFrame

try:
  # %tensorflow_version only exists in Colab.
#   %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers

print(tf.__version__)

from google.colab import drive
drive.mount('/content/drive')

import keras
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras import Sequential
import pandas as pd
import numpy as  np
import matplotlib.pyplot as plt

df = pd.read_csv('drive/My Drive/Colab Notebooks/Standford2.csv',sep=',')
df.head()

Fechas = df[['Dates']].values
Signal = df[['Signal']].values

print("Muestras totales medidas: ", df['Dates'].nunique())
M = df['Dates'].nunique()

sns.pairplot(df[["Dates", "Signal"]], diag_kind="kde")
#Estadísticas generales
train_stats = df.describe()
train_stats

Dataset = DataFrame(df,columns=['Dates','Signal'])
print(df)

df.plot(x ='Dates', y='Signal', kind = 'line',figsize=(30,5))
plt.xlabel('Dates')
plt.ylabel('Magnitude')
plt.show()

#from scipy import fftpack

#X = fftpack.fft(Signal)

#freqs = fftpack.fftfreq(len(x)) * f_s

#fig, ax = plt.subplots()

#ax.stem(freqs, np.abs(X))
#ax.set_xlabel('Frequency in Hertz [Hz]')
#ax.set_ylabel('Frequency Domain (Spectrum) Magnitude')
#ax.set_xlim(-f_s / 2, f_s / 2)
#ax.set_ylim(-5, 110)



